### ISSUE TITLE
Home page links

### ISSUE THREAD

**Issue by nzabajp** [francofgp/Engineered#1]
The 'latest post' links seem to not be working when accessed via the home page

**Comment by francofgp** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/70602890/169723445-18895d71-9135-4b08-9bac-1110d2a6c72d.png)
It is just a hover effect, the Home page, always shows you the latest 3 posts that you have created

The /posts, shows you all the posts created

**Comment by nzabajp** [comment]
I meant the "continue reading" links that are on the 2 posts under the "Latest Posts" heading. They don't work when you try to access them from the home page.

![Screenshot from 2022-05-23 09-46-00](https://user-images.githubusercontent.com/104729577/169769538-4d3736ca-0cc8-4c5f-86ed-5131a8bbb884.png)
![Screenshot from 2022-05-23 09-44-35](https://user-images.githubusercontent.com/104729577/169769548-2fe107ff-39eb-4dc8-a23c-d3c8effdfbb2.png)

**Comment by francofgp** [comment]
Oh, nice catch. I will fix it as soon as I can.

**Comment by francofgp** [comment]
Fixed
